-- 每日选股擂台：Supabase 在线共创数据库
-- 运行位置：Supabase Dashboard -> SQL Editor -> New query -> Run
-- 当前权限模式：任何拿到网站地址的人都可以读取和修改主比赛数据。

begin;

create table if not exists public.competition_state (
  id text primary key,
  revision bigint not null default 1 check (revision > 0),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by jsonb not null default '{}'::jsonb,
  constraint competition_state_main_id check (id = 'main')
);

create table if not exists public.competition_state_history (
  history_id bigint generated by default as identity primary key,
  state_id text not null,
  revision bigint not null,
  payload jsonb not null,
  updated_at timestamptz not null,
  updated_by jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now(),
  unique (state_id, revision)
);

create index if not exists competition_state_history_recorded_at_idx
  on public.competition_state_history (recorded_at desc);

create or replace function public.bump_competition_state_revision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.revision := old.revision + 1;
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.archive_competition_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.competition_state_history (
    state_id,
    revision,
    payload,
    updated_at,
    updated_by
  ) values (
    new.id,
    new.revision,
    new.payload,
    new.updated_at,
    new.updated_by
  )
  on conflict (state_id, revision) do nothing;
  return new;
end;
$$;

drop trigger if exists competition_state_bump_revision on public.competition_state;
create trigger competition_state_bump_revision
before update on public.competition_state
for each row execute function public.bump_competition_state_revision();

drop trigger if exists competition_state_archive on public.competition_state;
create trigger competition_state_archive
after insert or update on public.competition_state
for each row execute function public.archive_competition_state();

alter table public.competition_state enable row level security;
alter table public.competition_state_history enable row level security;
alter table public.competition_state replica identity full;

-- 公开共创模式：访客无需登录即可读取、新建和更新 main 记录。
drop policy if exists competition_state_public_read on public.competition_state;
create policy competition_state_public_read
on public.competition_state
for select
to anon, authenticated
using (id = 'main');

drop policy if exists competition_state_public_insert on public.competition_state;
create policy competition_state_public_insert
on public.competition_state
for insert
to anon, authenticated
with check (id = 'main' and revision = 1);

drop policy if exists competition_state_public_update on public.competition_state;
create policy competition_state_public_update
on public.competition_state
for update
to anon, authenticated
using (id = 'main')
with check (id = 'main');

-- 不允许前端直接删除主记录，也不开放历史表。
revoke delete on public.competition_state from anon, authenticated;
revoke all on public.competition_state_history from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.competition_state to anon, authenticated;

-- 开启 Postgres Changes 实时同步；重复执行此文件不会重复添加。
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'competition_state'
  ) then
    execute 'alter publication supabase_realtime add table public.competition_state';
  end if;
end;
$$;

commit;
